import { resolve } from "node:path";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { mkdirSync } from "node:fs";
import type { RepoAggregation } from "../models/cluster.js";
import { readJSON } from "../utils/cache.js";
import { repoSlug, type RepoConfig } from "../config/repos.js";
import {
  generateRankingTable,
  generateRisingTable,
  getWeekString,
  type Lang,
} from "../utils/markdown.js";
import { TOP_N_REPORT } from "../config/constants.js";
import { logger } from "../utils/logger.js";

const PUBLIC_SITE_URL = "https://study8677.github.io/ReadYourUsers/";
const PUBLIC_SITE_EN_URL = `${PUBLIC_SITE_URL}en/index.html`;
const PUBLIC_SITE_ZH_URL = `${PUBLIC_SITE_URL}zh/index.html`;

export interface GenerateOptions {
  repo: string;
  repoConfig: RepoConfig;
  dataDir: string;
  outputDir: string;
}

export interface GenerateResult {
  repo: string;
  reportPath: string;
  readmeUpdated: boolean;
}

export async function generateReports(
  options: GenerateOptions
): Promise<GenerateResult> {
  const { repo, repoConfig, dataDir, outputDir } = options;

  const slug = repoSlug(repo);
  const clustersPath = resolve(dataDir, "aggregated", slug, "clusters.json");

  const aggregation = readJSON<RepoAggregation>(clustersPath);
  if (!aggregation || aggregation.clusters.length === 0) {
    throw new Error(
      `No aggregated data found at ${clustersPath}. Run 'ryu aggregate ${repo}' first.`
    );
  }

  const week = getWeekString();
  const now = new Date();

  const byDemand = [...aggregation.clusters].sort(
    (a, b) => b.demand_score - a.demand_score
  );
  const byRising = [...aggregation.clusters]
    .filter((c) => c.rising_score > 1)
    .sort((a, b) => b.rising_score - a.rising_score);

  // Generate both English and Chinese reports
  for (const lang of ["en", "zh"] as Lang[]) {
    const report = generateWeeklyReportMd(aggregation, repoConfig, byDemand, byRising, week, now, lang);
    const suffix = lang === "zh" ? ".zh" : "";

    const latestDir = resolve(outputDir, "latest");
    mkdirSync(latestDir, { recursive: true });
    const latestPath = resolve(latestDir, `${slug}${suffix}.md`);
    writeFileSync(latestPath, report, "utf-8");

    const archiveDir = resolve(outputDir, "archive", week);
    mkdirSync(archiveDir, { recursive: true });
    const archivePath = resolve(archiveDir, `${slug}${suffix}.md`);
    writeFileSync(archivePath, report, "utf-8");

    logger.info(`${lang.toUpperCase()} report written to ${latestPath}`);
  }

  const readmeUpdated = updateReadme(
    repo,
    repoConfig,
    aggregation,
    byDemand,
    byRising,
    now
  );

  return {
    repo,
    reportPath: resolve(outputDir, "latest", `${slug}.md`),
    readmeUpdated,
  };
}

// =====================================================
// i18n labels
// =====================================================
const labels = {
  en: {
    reportTitle: (name: string) => `${name} — User Demand Report`,
    week: "Week",
    generated: "Generated",
    issuesAnalyzed: "Issues analyzed",
    included: "included",
    needClusters: "Need clusters",
    topNeeds: "Top 10 User Needs",
    risingNeeds: "Rising Needs",
    categoryBreakdown: "Category Breakdown",
    clusters: "clusters",
    allClusters: "All Need Clusters",
    volume: "Volume",
    issues: "issues",
    open: "open",
    closed: "closed",
    demandScore: "Demand Score",
    avgReactions: "Avg Reactions",
    avgComments: "Avg Comments",
    exampleIssues: "Example issues",
    footer:
      "*This report analyzes public GitHub issues only. It represents a signal from public issue discussions, not the full user base.*",
    generatedBy: "*Generated by [ReadYourUsers](https://github.com/fanjingwen/ReadYourUsers)*",
  },
  zh: {
    reportTitle: (name: string) => `${name} — 用户需求报告`,
    week: "周",
    generated: "生成日期",
    issuesAnalyzed: "分析 Issue 数",
    included: "纳入分析",
    needClusters: "需求簇",
    topNeeds: "Top 10 用户需求",
    risingNeeds: "上升最快的需求",
    categoryBreakdown: "分类分布",
    clusters: "个簇",
    allClusters: "所有需求簇",
    volume: "数量",
    issues: "条 issue",
    open: "未关闭",
    closed: "已关闭",
    demandScore: "需求得分",
    avgReactions: "平均反应",
    avgComments: "平均评论",
    exampleIssues: "示例 Issue",
    footer:
      "*本报告仅分析公开 GitHub Issues，代表的是公开讨论中的需求信号，并非全部用户的声音。*",
    generatedBy: "*由 [ReadYourUsers](https://github.com/fanjingwen/ReadYourUsers) 生成*",
  },
} as const;

function generateWeeklyReportMd(
  aggregation: RepoAggregation,
  repoConfig: RepoConfig,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  week: string,
  now: Date,
  lang: Lang
): string {
  const t = labels[lang];
  const lines: string[] = [];

  lines.push(`# ${t.reportTitle(repoConfig.display_name)}`);
  lines.push("");
  lines.push(`**${t.week}:** ${week}`);
  lines.push(`**${t.generated}:** ${now.toISOString().slice(0, 10)}`);
  lines.push(
    `**${t.issuesAnalyzed}:** ${aggregation.total_issues_analyzed} (${aggregation.total_issues_included} ${t.included})`
  );
  lines.push(`**${t.needClusters}:** ${aggregation.clusters.length}`);
  lines.push("");

  lines.push(`## ${t.topNeeds}`);
  lines.push("");
  lines.push(generateRankingTable(byDemand, TOP_N_REPORT, lang));
  lines.push("");

  if (byRising.length > 0) {
    lines.push(`## ${t.risingNeeds}`);
    lines.push("");
    lines.push(generateRisingTable(byRising, 5, lang));
    lines.push("");
  }

  lines.push(`## ${t.categoryBreakdown}`);
  lines.push("");
  const categories = Object.entries(aggregation.category_breakdown)
    .sort((a, b) => b[1] - a[1]);
  for (const [cat, count] of categories) {
    lines.push(`- **${cat}**: ${count} ${t.clusters}`);
  }
  lines.push("");

  lines.push(`## ${t.allClusters}`);
  lines.push("");
  for (let i = 0; i < byDemand.length; i++) {
    const c = byDemand[i];
    lines.push(`### ${i + 1}. ${c.title}`);
    lines.push("");
    lines.push(c.summary);
    lines.push("");
    lines.push(
      `- **${t.volume}:** ${c.volume} ${t.issues} (${c.open_count} ${t.open}, ${c.closed_count} ${t.closed})`
    );
    lines.push(`- **${t.demandScore}:** ${c.demand_score.toFixed(1)}`);
    lines.push(
      `- **${t.avgReactions}:** ${c.avg_reactions} | **${t.avgComments}:** ${c.avg_comments}`
    );

    const issueLinks = c.issue_urls
      .slice(0, 5)
      .map((url) => {
        const num = url.split("/").pop();
        return `[#${num}](${url})`;
      })
      .join(", ");
    lines.push(`- **${t.exampleIssues}:** ${issueLinks}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(t.footer);
  lines.push("");
  lines.push(t.generatedBy);

  return lines.join("\n");
}

function updateReadme(
  repo: string,
  repoConfig: RepoConfig,
  aggregation: RepoAggregation,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  now: Date
): boolean {
  const slug = repoSlug(repo);
  const marker = {
    start: "<!-- READYOURUSERS:START -->",
    end: "<!-- READYOURUSERS:END -->",
  };

  // ===================== English README.md =====================
  writeReadmeFile(
    resolve(process.cwd(), "README.md"),
    marker,
    buildEnglishReadme(repo, repoConfig, slug, aggregation, byDemand, byRising, now)
  );

  // ===================== Chinese README.zh.md =====================
  writeReadmeFile(
    resolve(process.cwd(), "README.zh.md"),
    marker,
    buildChineseReadme(repo, repoConfig, slug, aggregation, byDemand, byRising, now)
  );

  logger.info("README.md + README.zh.md updated");
  return true;
}

function writeReadmeFile(
  path: string,
  marker: { start: string; end: string },
  content: { section: string; fullPage: string }
): void {
  if (existsSync(path)) {
    let readme = readFileSync(path, "utf-8");
    const startIdx = readme.indexOf(marker.start);
    const endIdx = readme.indexOf(marker.end);
    if (startIdx !== -1 && endIdx !== -1) {
      readme =
        readme.slice(0, startIdx) +
        content.section +
        readme.slice(endIdx + marker.end.length);
    } else {
      readme += "\n\n" + content.section;
    }
    writeFileSync(path, readme, "utf-8");
  } else {
    writeFileSync(path, content.fullPage, "utf-8");
  }
}

function buildEnglishReadme(
  repo: string,
  repoConfig: RepoConfig,
  slug: string,
  aggregation: RepoAggregation,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  now: Date
): { section: string; fullPage: string } {
  const s: string[] = [];
  s.push("<!-- READYOURUSERS:START -->");
  s.push("");
  s.push(`## Live snapshot — ${repoConfig.display_name}`);
  s.push("");
  s.push(
    `> ${aggregation.total_issues_analyzed} issues analyzed from [${repo}](https://github.com/${repo}) · ` +
    `${aggregation.clusters.length} need clusters · ` +
    `Updated ${now.toISOString().slice(0, 10)}`
  );
  s.push("");
  s.push("### Top needs right now");
  s.push("");
  s.push(generateRankingTable(byDemand, TOP_N_REPORT, "en"));
  s.push("");
  if (byRising.length > 0) {
    s.push("### Rising fastest");
    s.push("");
    s.push(generateRisingTable(byRising, 5, "en"));
    s.push("");
  }
  s.push(
    `[Live site](${PUBLIC_SITE_URL}) | ` +
    `[English site](${PUBLIC_SITE_EN_URL}) | ` +
    `[中文站点](${PUBLIC_SITE_ZH_URL}) | ` +
    `[Full report](reports/latest/${slug}.md) | ` +
    `[中文版](README.zh.md) | ` +
    `*Based on public GitHub issues — signal, not census.*`
  );
  s.push("");
  s.push("<!-- READYOURUSERS:END -->");
  const section = s.join("\n");

  const fullPage = `# ReadYourUsers

> Understand what users actually want by turning public GitHub issues into ranked demand maps.

ReadYourUsers is a TypeScript CLI and static site generator for turning noisy GitHub issue streams into something product teams can actually use:

- ranked user needs
- rising trends
- traceable evidence back to the original issues
- bilingual reports and a bilingual public site

**Links:** [Live site](${PUBLIC_SITE_URL}) · [English](${PUBLIC_SITE_EN_URL}) · [中文](${PUBLIC_SITE_ZH_URL}) · [中文版 README](README.zh.md)

${section}

## Why ReadYourUsers

Reading issues one by one does not scale.

- titles are inconsistent
- duplicates are spread across many threads
- urgency is easy to miss
- recent momentum is buried in a long list of issues

ReadYourUsers turns that raw stream into a compact demand map you can scan in minutes.

## What you get

- **Ranked needs** — clustered requests with demand scores
- **Rising signals** — what is accelerating right now
- **Traceability** — every insight links back to source issues
- **Bilingual outputs** — English and Chinese reports plus a bilingual site
- **Repeatable pipeline** — fetch, analyze, aggregate, publish

## Quick start

### Requirements

- Node.js 18+
- a GitHub token for reading public issues
- an LLM key for either Anthropic or OpenAI-compatible APIs

### Install

\`\`\`bash
npm install
cp .env.example .env
\`\`\`

### Run the full pipeline

\`\`\`bash
npx tsx src/cli.ts run anthropics/claude-code
\`\`\`

### Run step by step

\`\`\`bash
npx tsx src/cli.ts fetch anthropics/claude-code
npx tsx src/cli.ts analyze anthropics/claude-code
npx tsx src/cli.ts aggregate anthropics/claude-code
npx tsx src/cli.ts generate anthropics/claude-code
\`\`\`

## How it works

1. **Fetch** — pull public issues from GitHub with caching
2. **Analyze** — use an LLM to extract structured need signals
3. **Aggregate** — cluster similar needs and compute demand / rising scores
4. **Generate** — publish Markdown reports, site pages, and README snapshots

## Outputs

\`\`\`text
reports/latest/<repo>.md
reports/latest/<repo>.zh.md
reports/archive/<week>/<repo>.md
reports/archive/<week>/<repo>.zh.md
site/en/...
site/zh/...
README.md
README.zh.md
\`\`\`

## Tracked repositories

| Repository | Product | Category |
| --- | --- | --- |
| [anthropics/claude-code](https://github.com/anthropics/claude-code) | Claude Code | AI Coding CLI |
| [openai/codex](https://github.com/openai/codex) | OpenAI Codex CLI | AI Coding Agent |
| [getcursor/cursor](https://github.com/getcursor/cursor) | Cursor | AI Code Editor |

## Limits

- **Public data only** — private support channels are not included
- **Signal, not census** — issue volume is not the same as total user count
- **LLM summarization is imperfect** — conclusions stay grounded by linking back to the source issues
- **Feedback quality varies by product** — some products rely less on GitHub issues than others

## Principles

- **Public-data only**
- **Traceable conclusions**
- **Fast to scan**
- **Useful for product decisions, not just issue triage**

## License

MIT
`;
  return { section, fullPage };
}

function buildChineseReadme(
  repo: string,
  repoConfig: RepoConfig,
  slug: string,
  aggregation: RepoAggregation,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  now: Date
): { section: string; fullPage: string } {
  const s: string[] = [];
  s.push("<!-- READYOURUSERS:START -->");
  s.push("");
  s.push(`## 实时快照 — ${repoConfig.display_name}`);
  s.push("");
  s.push(
    `> 基于 [${repo}](https://github.com/${repo}) 的 ${aggregation.total_issues_analyzed} 条 issue · ` +
    `${aggregation.clusters.length} 个需求簇 · ` +
    `更新于 ${now.toISOString().slice(0, 10)}`
  );
  s.push("");
  s.push("### 当前最强需求");
  s.push("");
  s.push(generateRankingTable(byDemand, TOP_N_REPORT, "zh"));
  s.push("");
  if (byRising.length > 0) {
    s.push("### 上升最快");
    s.push("");
    s.push(generateRisingTable(byRising, 5, "zh"));
    s.push("");
  }
  s.push(
    `[在线网页](${PUBLIC_SITE_URL}) | ` +
    `[English site](${PUBLIC_SITE_EN_URL}) | ` +
    `[中文站点](${PUBLIC_SITE_ZH_URL}) | ` +
    `[完整报告](reports/latest/${slug}.zh.md) | ` +
    `[English](README.md) | ` +
    `*基于公开 GitHub Issues，代表需求信号而非全部用户声音。*`
  );
  s.push("");
  s.push("<!-- READYOURUSERS:END -->");
  const section = s.join("\n");

  const fullPage = `# ReadYourUsers

> 把公开 GitHub Issues 变成可读、可排序、可追溯的用户需求地图。

ReadYourUsers 是一个 TypeScript CLI + 静态站点生成器，用来把嘈杂的 GitHub issue 流整理成产品团队真正能用的需求信号：

- 有排序的用户需求
- 正在上升的趋势
- 可以追溯到原始 issue 的证据链
- 中英双语报告和双语网站

**链接：** [在线网页](${PUBLIC_SITE_URL}) · [English](${PUBLIC_SITE_EN_URL}) · [中文](${PUBLIC_SITE_ZH_URL}) · [English README](README.md)

${section}

## 为什么值得做

直接看 issue 不够高效：

- 标题表达不统一
- 重复需求分散在不同线程
- 紧迫度不容易一眼看出
- 最近正在升温的问题常常埋在长列表里

ReadYourUsers 把这些原始讨论压缩成一张几分钟就能扫完的需求地图。

## 你能得到什么

- **需求排行** — 聚类后的核心用户需求与 demand score
- **上升趋势** — 最近正在加速出现的问题
- **可追溯证据** — 每条结论都能回到原始 issue
- **双语输出** — 英文 / 中文报告与双语站点
- **可复用流水线** — 抓取、分析、聚合、发布一条龙

## 快速开始

### 环境要求

- Node.js 18+
- 用于读取公开 issue 的 GitHub token
- Anthropic 或 OpenAI 兼容接口的 LLM key

### 安装

\`\`\`bash
npm install
cp .env.example .env
\`\`\`

### 跑完整流程

\`\`\`bash
npx tsx src/cli.ts run anthropics/claude-code
\`\`\`

### 分步执行

\`\`\`bash
npx tsx src/cli.ts fetch anthropics/claude-code
npx tsx src/cli.ts analyze anthropics/claude-code
npx tsx src/cli.ts aggregate anthropics/claude-code
npx tsx src/cli.ts generate anthropics/claude-code
\`\`\`

## 工作原理

1. **抓取** — 从 GitHub 拉取公开 issue，并做缓存
2. **分析** — 用 LLM 提取结构化需求信号
3. **聚合** — 聚类相似需求，计算 demand / rising score
4. **生成** — 发布 Markdown 报告、站点页面和 README 快照

## 产物

\`\`\`text
reports/latest/<repo>.md
reports/latest/<repo>.zh.md
reports/archive/<week>/<repo>.md
reports/archive/<week>/<repo>.zh.md
site/en/...
site/zh/...
README.md
README.zh.md
\`\`\`

## 当前追踪的仓库

| 仓库 | 产品 | 分类 |
| --- | --- | --- |
| [anthropics/claude-code](https://github.com/anthropics/claude-code) | Claude Code | AI 编程 CLI |
| [openai/codex](https://github.com/openai/codex) | OpenAI Codex CLI | AI 编程 Agent |
| [getcursor/cursor](https://github.com/getcursor/cursor) | Cursor | AI 代码编辑器 |

## 局限

- **只看公开数据** — 私有支持渠道不包含在内
- **信号不是普查** — issue 数量不等于真实总用户数
- **LLM 总结不是完美的** — 所以必须保留可追溯链接
- **不同产品的 GitHub 活跃度不同** — 跨产品比较要谨慎

## 原则

- **只用公开数据**
- **结论必须可追溯**
- **优先可快速扫描**
- **服务产品判断，而不只是 issue 整理**

## License

MIT
`;
  return { section, fullPage };
}
