import { resolve } from "node:path";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { mkdirSync } from "node:fs";
import type { RepoAggregation } from "../models/cluster.js";
import { readJSON } from "../utils/cache.js";
import { repoSlug, type RepoConfig } from "../config/repos.js";
import {
  generateRankingTable,
  generateRisingTable,
  getWeekString,
  type Lang,
} from "../utils/markdown.js";
import { TOP_N_REPORT } from "../config/constants.js";
import { logger } from "../utils/logger.js";

const PUBLIC_SITE_URL = "https://study8677.github.io/ReadYourUsers/";

export interface GenerateOptions {
  repo: string;
  repoConfig: RepoConfig;
  dataDir: string;
  outputDir: string;
}

export interface GenerateResult {
  repo: string;
  reportPath: string;
  readmeUpdated: boolean;
}

export async function generateReports(
  options: GenerateOptions
): Promise<GenerateResult> {
  const { repo, repoConfig, dataDir, outputDir } = options;

  const slug = repoSlug(repo);
  const clustersPath = resolve(dataDir, "aggregated", slug, "clusters.json");

  const aggregation = readJSON<RepoAggregation>(clustersPath);
  if (!aggregation || aggregation.clusters.length === 0) {
    throw new Error(
      `No aggregated data found at ${clustersPath}. Run 'ryu aggregate ${repo}' first.`
    );
  }

  const week = getWeekString();
  const now = new Date();

  const byDemand = [...aggregation.clusters].sort(
    (a, b) => b.demand_score - a.demand_score
  );
  const byRising = [...aggregation.clusters]
    .filter((c) => c.rising_score > 1)
    .sort((a, b) => b.rising_score - a.rising_score);

  // Generate both English and Chinese reports
  for (const lang of ["en", "zh"] as Lang[]) {
    const report = generateWeeklyReportMd(aggregation, repoConfig, byDemand, byRising, week, now, lang);
    const suffix = lang === "zh" ? ".zh" : "";

    const latestDir = resolve(outputDir, "latest");
    mkdirSync(latestDir, { recursive: true });
    const latestPath = resolve(latestDir, `${slug}${suffix}.md`);
    writeFileSync(latestPath, report, "utf-8");

    const archiveDir = resolve(outputDir, "archive", week);
    mkdirSync(archiveDir, { recursive: true });
    const archivePath = resolve(archiveDir, `${slug}${suffix}.md`);
    writeFileSync(archivePath, report, "utf-8");

    logger.info(`${lang.toUpperCase()} report written to ${latestPath}`);
  }

  const readmeUpdated = updateReadme(
    repo,
    repoConfig,
    aggregation,
    byDemand,
    byRising,
    now
  );

  return {
    repo,
    reportPath: resolve(outputDir, "latest", `${slug}.md`),
    readmeUpdated,
  };
}

// =====================================================
// i18n labels
// =====================================================
const labels = {
  en: {
    reportTitle: (name: string) => `${name} — User Demand Report`,
    week: "Week",
    generated: "Generated",
    issuesAnalyzed: "Issues analyzed",
    included: "included",
    needClusters: "Need clusters",
    topNeeds: "Top 10 User Needs",
    risingNeeds: "Rising Needs",
    categoryBreakdown: "Category Breakdown",
    clusters: "clusters",
    allClusters: "All Need Clusters",
    volume: "Volume",
    issues: "issues",
    open: "open",
    closed: "closed",
    demandScore: "Demand Score",
    avgReactions: "Avg Reactions",
    avgComments: "Avg Comments",
    exampleIssues: "Example issues",
    footer:
      "*This report analyzes public GitHub issues only. It represents a signal from public issue discussions, not the full user base.*",
    generatedBy: "*Generated by [ReadYourUsers](https://github.com/fanjingwen/ReadYourUsers)*",
  },
  zh: {
    reportTitle: (name: string) => `${name} — 用户需求报告`,
    week: "周",
    generated: "生成日期",
    issuesAnalyzed: "分析 Issue 数",
    included: "纳入分析",
    needClusters: "需求簇",
    topNeeds: "Top 10 用户需求",
    risingNeeds: "上升最快的需求",
    categoryBreakdown: "分类分布",
    clusters: "个簇",
    allClusters: "所有需求簇",
    volume: "数量",
    issues: "条 issue",
    open: "未关闭",
    closed: "已关闭",
    demandScore: "需求得分",
    avgReactions: "平均反应",
    avgComments: "平均评论",
    exampleIssues: "示例 Issue",
    footer:
      "*本报告仅分析公开 GitHub Issues，代表的是公开讨论中的需求信号，并非全部用户的声音。*",
    generatedBy: "*由 [ReadYourUsers](https://github.com/fanjingwen/ReadYourUsers) 生成*",
  },
} as const;

function generateWeeklyReportMd(
  aggregation: RepoAggregation,
  repoConfig: RepoConfig,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  week: string,
  now: Date,
  lang: Lang
): string {
  const t = labels[lang];
  const lines: string[] = [];

  lines.push(`# ${t.reportTitle(repoConfig.display_name)}`);
  lines.push("");
  lines.push(`**${t.week}:** ${week}`);
  lines.push(`**${t.generated}:** ${now.toISOString().slice(0, 10)}`);
  lines.push(
    `**${t.issuesAnalyzed}:** ${aggregation.total_issues_analyzed} (${aggregation.total_issues_included} ${t.included})`
  );
  lines.push(`**${t.needClusters}:** ${aggregation.clusters.length}`);
  lines.push("");

  lines.push(`## ${t.topNeeds}`);
  lines.push("");
  lines.push(generateRankingTable(byDemand, TOP_N_REPORT, lang));
  lines.push("");

  if (byRising.length > 0) {
    lines.push(`## ${t.risingNeeds}`);
    lines.push("");
    lines.push(generateRisingTable(byRising, 5, lang));
    lines.push("");
  }

  lines.push(`## ${t.categoryBreakdown}`);
  lines.push("");
  const categories = Object.entries(aggregation.category_breakdown)
    .sort((a, b) => b[1] - a[1]);
  for (const [cat, count] of categories) {
    lines.push(`- **${cat}**: ${count} ${t.clusters}`);
  }
  lines.push("");

  lines.push(`## ${t.allClusters}`);
  lines.push("");
  for (let i = 0; i < byDemand.length; i++) {
    const c = byDemand[i];
    lines.push(`### ${i + 1}. ${c.title}`);
    lines.push("");
    lines.push(c.summary);
    lines.push("");
    lines.push(
      `- **${t.volume}:** ${c.volume} ${t.issues} (${c.open_count} ${t.open}, ${c.closed_count} ${t.closed})`
    );
    lines.push(`- **${t.demandScore}:** ${c.demand_score.toFixed(1)}`);
    lines.push(
      `- **${t.avgReactions}:** ${c.avg_reactions} | **${t.avgComments}:** ${c.avg_comments}`
    );

    const issueLinks = c.issue_urls
      .slice(0, 5)
      .map((url) => {
        const num = url.split("/").pop();
        return `[#${num}](${url})`;
      })
      .join(", ");
    lines.push(`- **${t.exampleIssues}:** ${issueLinks}`);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(t.footer);
  lines.push("");
  lines.push(t.generatedBy);

  return lines.join("\n");
}

function updateReadme(
  repo: string,
  repoConfig: RepoConfig,
  aggregation: RepoAggregation,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  now: Date
): boolean {
  const slug = repoSlug(repo);
  const marker = {
    start: "<!-- READYOURUSERS:START -->",
    end: "<!-- READYOURUSERS:END -->",
  };

  // ===================== English README.md =====================
  writeReadmeFile(
    resolve(process.cwd(), "README.md"),
    marker,
    buildEnglishReadme(repo, repoConfig, slug, aggregation, byDemand, byRising, now)
  );

  // ===================== Chinese README.zh.md =====================
  writeReadmeFile(
    resolve(process.cwd(), "README.zh.md"),
    marker,
    buildChineseReadme(repo, repoConfig, slug, aggregation, byDemand, byRising, now)
  );

  logger.info("README.md + README.zh.md updated");
  return true;
}

function writeReadmeFile(
  path: string,
  marker: { start: string; end: string },
  content: { section: string; fullPage: string }
): void {
  if (existsSync(path)) {
    let readme = readFileSync(path, "utf-8");
    const startIdx = readme.indexOf(marker.start);
    const endIdx = readme.indexOf(marker.end);
    if (startIdx !== -1 && endIdx !== -1) {
      readme =
        readme.slice(0, startIdx) +
        content.section +
        readme.slice(endIdx + marker.end.length);
    } else {
      readme += "\n\n" + content.section;
    }
    writeFileSync(path, readme, "utf-8");
  } else {
    writeFileSync(path, content.fullPage, "utf-8");
  }
}

function buildEnglishReadme(
  repo: string,
  repoConfig: RepoConfig,
  slug: string,
  aggregation: RepoAggregation,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  now: Date
): { section: string; fullPage: string } {
  const s: string[] = [];
  s.push("<!-- READYOURUSERS:START -->");
  s.push("");
  s.push("## AI Coding Tools — What Developers Really Want");
  s.push("");
  s.push(
    `> **${aggregation.total_issues_analyzed}** issues analyzed from [${repo}](https://github.com/${repo}) | ` +
    `**${aggregation.clusters.length}** need clusters | ` +
    `Updated ${now.toISOString().slice(0, 10)}`
  );
  s.push("");
  s.push("### Top 10 Needs");
  s.push("");
  s.push(generateRankingTable(byDemand, TOP_N_REPORT, "en"));
  s.push("");
  if (byRising.length > 0) {
    s.push("### Rising Needs");
    s.push("");
    s.push(generateRisingTable(byRising, 5, "en"));
    s.push("");
  }
  s.push(
    `[Live site](${PUBLIC_SITE_URL}) | ` +
    `[Full report](reports/latest/${slug}.md) | ` +
    `[中文版](README.zh.md) | ` +
    `*Based on public GitHub issues — signal, not census.*`
  );
  s.push("");
  s.push("<!-- READYOURUSERS:END -->");
  const section = s.join("\n");

  const fullPage = `# ReadYourUsers

> Turn public GitHub issues into readable **user demand maps**.

We analyze thousands of public issues from the most active AI coding tool repositories and distill them into a ranked, clustered weekly report — so you can see what developers actually want at a glance.

**[中文版 README](README.zh.md)**

**[Live site](${PUBLIC_SITE_URL})**

${section}

## How It Works

\`\`\`
GitHub Issues ──► Fetch ──► LLM Analyze ──► Cluster & Rank ──► Report
                  (Octokit)   (per-issue)    (demand score)     (Markdown)
\`\`\`

1. **Fetch** — Pull public issues from target repositories via GitHub API (pagination, etag caching, incremental)
2. **Analyze** — LLM extracts structured need signals from each issue (type, normalized need, module tags, severity)
3. **Aggregate** — Cluster similar needs by module, compute demand & rising scores
4. **Generate** — Produce ranked reports with links back to every original issue

## Quick Start

\`\`\`bash
npm install
cp .env.example .env    # add your API keys
npx tsx src/cli.ts run anthropics/claude-code
\`\`\`

## Tracked Repositories

| Repository | Product | Category |
| --- | --- | --- |
| [anthropics/claude-code](https://github.com/anthropics/claude-code) | Claude Code | AI Coding CLI |
| [openai/codex](https://github.com/openai/codex) | OpenAI Codex CLI | AI Coding Agent |
| [getcursor/cursor](https://github.com/getcursor/cursor) | Cursor | AI Code Editor |

## Reports

- [Live site](${PUBLIC_SITE_URL})
- [Latest English report](reports/latest/${slug}.md)
- [Latest Chinese report](reports/latest/${slug}.zh.md)
- [Archived weekly reports](reports/archive/)

## Principles

- **Public data only** — We only analyze public GitHub issues
- **Traceable** — Every insight links to original issues
- **Signal, not census** — Public discussions, not all users
- **No contact scraping** — We never collect personal information

## License

MIT
`;
  return { section, fullPage };
}

function buildChineseReadme(
  repo: string,
  repoConfig: RepoConfig,
  slug: string,
  aggregation: RepoAggregation,
  byDemand: RepoAggregation["clusters"],
  byRising: RepoAggregation["clusters"],
  now: Date
): { section: string; fullPage: string } {
  const s: string[] = [];
  s.push("<!-- READYOURUSERS:START -->");
  s.push("");
  s.push("## AI 编程工具 — 开发者真正想要什么");
  s.push("");
  s.push(
    `> 从 [${repo}](https://github.com/${repo}) 分析了 **${aggregation.total_issues_analyzed}** 条 issue | ` +
    `**${aggregation.clusters.length}** 个需求簇 | ` +
    `更新于 ${now.toISOString().slice(0, 10)}`
  );
  s.push("");
  s.push("### Top 10 需求");
  s.push("");
  s.push(generateRankingTable(byDemand, TOP_N_REPORT, "zh"));
  s.push("");
  if (byRising.length > 0) {
    s.push("### 上升最快的需求");
    s.push("");
    s.push(generateRisingTable(byRising, 5, "zh"));
    s.push("");
  }
  s.push(
    `[在线网页](${PUBLIC_SITE_URL}) | ` +
    `[完整报告](reports/latest/${slug}.zh.md) | ` +
    `[English](README.md) | ` +
    `*基于公开 GitHub Issues，代表需求信号而非全部用户声音。*`
  );
  s.push("");
  s.push("<!-- READYOURUSERS:END -->");
  const section = s.join("\n");

  const fullPage = `# ReadYourUsers

> 把公开 GitHub Issues 变成可读的**用户需求地图**。

我们分析 AI 编程工具最活跃仓库中的数千条公开 issue，提炼成带排名、带聚类的周报 — 让你一眼看到开发者真正想要什么。

**[English README](README.md)**

**[在线网页](${PUBLIC_SITE_URL})**

${section}

## 工作原理

\`\`\`
GitHub Issues ──► 抓取 ──► LLM 分析 ──► 聚类 & 排名 ──► 报告
                  (Octokit)  (逐条分析)   (需求得分)      (Markdown)
\`\`\`

1. **抓取** — 通过 GitHub API 拉取目标仓库的公开 issues（分页、etag 缓存、增量更新）
2. **分析** — LLM 从每条 issue 中提取结构化需求信号（类型、归一需求、模块标签、严重程度）
3. **聚合** — 按模块聚类相似需求，计算需求分数和上升趋势
4. **生成** — 产出排行报告，每条结论都链接回原始 issue

## 快速开始

\`\`\`bash
npm install
cp .env.example .env    # 填入你的 API key
npx tsx src/cli.ts run anthropics/claude-code
\`\`\`

## 追踪的仓库

| 仓库 | 产品 | 分类 |
| --- | --- | --- |
| [anthropics/claude-code](https://github.com/anthropics/claude-code) | Claude Code | AI 编程 CLI |
| [openai/codex](https://github.com/openai/codex) | OpenAI Codex CLI | AI 编程 Agent |
| [getcursor/cursor](https://github.com/getcursor/cursor) | Cursor | AI 代码编辑器 |

## 报告

- [在线网页](${PUBLIC_SITE_URL})
- [最新英文报告](reports/latest/${slug}.md)
- [最新中文报告](reports/latest/${slug}.zh.md)
- [历史周报归档](reports/archive/)

## 原则

- **仅公开数据** — 只分析公开 GitHub Issues
- **可追溯** — 每条洞察都能链接到原始 issue
- **信号而非普查** — 代表公开讨论，不等于全部用户
- **不抓取联系方式** — 绝不收集个人信息

## License

MIT
`;
  return { section, fullPage };
}
